language: node_js
node_js:
- node
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
- npm i -g gl-transition-scripts
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
- "./scripts/build.sh"
before_deploy:
- cd release
deploy:
  provider: npm
  email: renaudeau.gaetan+gltransitions@gmail.com
  skip_cleanup: true
  api_key:
    secure: fyjUm2mDcCXLZOwf70aiAUAblCfHx5qfWrlKV2JoCIUkgdSgHfY99RlXS0yYXzTTSwbDrrGkjwgQNWjtmtdUQw5cipMnrVdBckYYLjWrGQm1elItfMF0yVT58rzLGYcMq9EWJifQKBTZJbWS+jQmyAV/bgU/fIAUn+U9xJ8sNHJH/sagPRF1VjOrJa8KcfpSITppj7nBomCWTSfEOZxjXjMyKIINYedB5xMLPy9JbNfPO9Mw7rZeFsM60Kj6cgeXM2Tc/s1FBz36AF28iyJCG2CPT1UPA8b9m5mpfKDLCgr6LDinCUniHk2KYAgg68sT1wQ/BAr/nEkNnUGTUQ4ZccEB5g537WarAQ6qTFfStbvXX+zSOtDgF0HOXibYFuOR+fOveAJn/Xb53V4IIRt9v5cYEDlfrvpA0ckZ3JreaMIyergP/GZEFfi4hvezicP4naq8RXME7F89jS7gGVv7A4etGDBp6AfWIwCJAOrTzY11HbFizdXfyDYgBMP+O/pEWMALlbmbEQOZJDFVND2eRMZi5D8NGkAV41bnlzNDWafrMlNNOmF8JcNKvoCwiMpBdgFXIHFnRJn0IAGBq3pGWfchEKv8NiyZdzCY4VWhzb0JRC/x8hd/9EbA120EFeQFwDs+j6uNwT1iEFlAQZPQdS+hOfZ6ffUxuilcpm448KI=
  on:
    repo: gltransitions/gl-transitions
    branch: master
after_deploy:
- "../scripts/tag-and-push.sh"
