language: node_js
node_js:
- node
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: cd scripts && yarn && yarn run build && cd -
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_deploy:
  - cd release
deploy:
  provider: npm
  email: renaudeau.gaetan@gmail.com
  skip_cleanup: true
  api_key:
    secure: QyW9GsET57UCYjOecJPxRc8Of0YWtKCgXKDWpsOy15wNmCZrKNp+xebjn/lBy2QDh5NRAlOQG4hyvcdo78Rskg7mvYPRBuGdSUv36LsvOZUPcCIvU/E8JV8DMh3Sc19OGgups2JHu9SZhU8+O5t3mDpA6HpM3qCSyTmML4meup6XIPgCvgXF36a9ZE1mDx9Tl7bz7TTyquBrjuHc8hetsVEKpzGIIKp/GD9k6dw+KslbIedy+B8V59CnlU2Agaka/Y6vDlYVAxUUg+81JG0p8x8fN3aTkZgOE4Hjl2hCfB9RUb+R+Ycn6E3BcCnmr+kBQfcLQZpyDurg6UcHhZjJ0TmP2CnWx79DIcUv+1c5uNgmm0teqO3bn0+b7uFHDNnMIBVT/xU4kcXMpUmAjaCILChB8Hm/7xhVpHXKH+dx69IHlqJ7sXK1/UuB7S97u7zgrsOMVzXKreE2M6e05NM0gMNq4bvp93qAsYopQSWmnjvRvAbrd3fsYKE0o5jdGUxjmaZcMHdTrc9xR/DFbH+usMXTmFIyHB8Q2DJYvCz+d63fK12E/CcX8dH355i86DMJCENF1GwcmcwdeUBnh7XY1JM7y84Mk6Kv3nmPVCVURompDGn8sg/9HCtmDwTBXrcuxRFufrAPnwih8ToLv02GLpzVrq/WwijzfQE0eDm8qJE=
  on:
    repo: gre/gl-transitions
    branch: master
